//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sshsv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClickLog
    {
        public int ID { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public Nullable<System.DateTime> clickTime { get; set; }
        public Nullable<bool> used { get; set; }
        public Nullable<int> clickID { get; set; }
        public string appName { get; set; }
        public string appID { get; set; }
        public string countryCode { get; set; }
        public string idfa { get; set; }
        public string iditune { get; set; }
        public string referrer { get; set; }
        public string version { get; set; }
        public string transactionID { get; set; }
    }
}
