//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sshsv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conversion
    {
        public int ID { get; set; }
        public Nullable<int> networkID { get; set; }
        public string offerID { get; set; }
        public string aff_source { get; set; }
        public string aff_subid1 { get; set; }
        public string aff_subid2 { get; set; }
        public string aff_subid3 { get; set; }
        public string session_ip { get; set; }
        public string payout { get; set; }
        public string device_brand { get; set; }
        public string device_model { get; set; }
        public string device_os { get; set; }
        public Nullable<System.DateTime> time_install { get; set; }
        public string country { get; set; }
        public Nullable<bool> postback { get; set; }
        public string transactionID { get; set; }
    
        public virtual network network { get; set; }
        public string server { get; set; }
        public string urlid { get; set; }
    }
}
