//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sshsv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class network
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public network()
        {
            this.conversions = new HashSet<conversion>();
        }
    
        public int ID { get; set; }
        public string networkName { get; set; }
        public string networkPb { get; set; }
        public Nullable<double> s_rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conversion> conversions { get; set; }
    }
}
