//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sshsv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ssh
    {
        public int ID { get; set; }
        public string ssh1 { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string used { get; set; }
        public Nullable<bool> live { get; set; }
    }
}
