//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sshsv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urlDB
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<int> ind { get; set; }
        public string network { get; set; }
        public Nullable<double> payout { get; set; }
    }
}
