//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sshsv {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sshsv.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0|1.0.0.255|Australia
        ///1.0.1.0|1.0.3.255|China
        ///1.0.4.0|1.0.7.255|Australia
        ///1.0.8.0|1.0.15.255|China
        ///1.0.16.0|1.0.31.255|Japan
        ///1.0.32.0|1.0.63.255|China
        ///1.0.64.0|1.0.127.255|Japan
        ///1.0.128.0|1.0.255.255|Thailand
        ///1.1.0.0|1.1.0.255|China
        ///1.1.1.0|1.1.1.255|Australia
        ///1.1.2.0|1.1.63.255|China
        ///1.1.64.0|1.1.127.255|Japan
        ///1.1.128.0|1.1.255.255|Thailand
        ///1.2.0.0|1.2.2.255|China
        ///1.2.3.0|1.2.3.255|United States
        ///1.2.4.0|1.2.127.255|China
        ///1.2.128.0|1.2.255.255|Thailand
        ///1.3.0.0|1.3.255.255|China
        ///1.4.0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string geo {
            get {
                return ResourceManager.GetString("geo", resourceCulture);
            }
        }
    }
}
